### PR TITLE
Fix mistransformation of type unions with comments

### LINKED ISSUE #351: mistransformation when comment inside type union
```lua
export type ReactNode =
  React_Element<any>
  | ReactPortal
--   | ReactText
  | ReactFragment
--   | ReactProvider<any>
--   | ReactConsumer<any>
```

currently formats to:
```lua
export type ReactNode = React_Element<any> | ReactPortal--   | ReactText
 | ReactFragment
--   | ReactProvider<any>
--   | ReactConsumer<any>
```

### PR DESCRIPTION
**Pull request by JohnnyMorganz**
Fixes #351,
Also fixes loss of comments when hanging a type union

### CODE REVIEW

File: tests/snapshots/tests__luau@type-union-comments.lua.snap [hunk 1]
```diff
@@ -0,0 +1,14 @@
+---
+source: tests/tests.rs
+expression: format(&contents)
+
+---
+-- https://github.com/JohnnyMorganz/StyLua/issues/351
+export type ReactNode =
+	React_Element<any>
+	| ReactPortal
+	--   | ReactText
```
Comment (matthargett) [inline tests/snapshots/tests__luau@type-union-comments.lua.snap:10]: Why does the ReactText comment get indented when the other comment don’t?
